const languages = {
  uz: {
    footer: {
      saved: "Saqlanganlar",
      backed: "Savatcha",
      contacts: "Kontaktlar",
      service: "Xizmat ko'rsatish shartlari",
    },

    service: {
      title: "Xizmat ko'rsatish shartlari",
      text: "Tashkilotning vazifasi, xususan, ijtimoiy yo'naltirilgan milliy loyiha yo'nalishi bizdan rivojlanish modelini tizimli ravishda tahlil qilishni talab qiladi! Shunday qilib, faoliyatimizni doimiy axborot va texnik qo'llab-quvvatlash bizdan bir qator parametrlarda keng ko'lamli o'zgarishlar tizimini tahlil qilishni talab qiladi! Boshqa tomondan, ijtimoiy-iqtisodiy rivojlanish to'g'ridan-to'g'ri har tomonlama muvozanatli innovatsiyalarga bog'liqmi?",
    },
    contacts: {
      title: "Bizning ofisimiz",
    },
    saved: {
      title: "Saqlanganlar",
    },
    emptybacked: {
      title: "Savatcha bo'sh",
      text: "Lekin buni to'g'irlash uchun hechqachon kech emas :)",
      button: "Mahsulotlar katalogiga",
    },
    product: {
      characteristicsTitle: "Opisanie va xarakteristikasi",
      buttonBuy: "Sotib olish!",
      addToBacked: "Savatchaga qo'shish",
    },
    cart: {
      title: "Savatcha",
      delivery: "Yetkazib berish",
      noDelivery: "Yetkazib berishsiz",
      byCourier: "Kuryer tomonidan yetgazib berish",
      total: "Jami",
      button: "Rasmiylashtirishga o'tish",
    },
    ordering: {
      title: "Buyurtma",
      addressTitle: "Yetgazib berish",
      address: "Yetkazib berish manzili",
      city: "Shahar",
      street: "Ko'cha / Tuman",
      house: "Uy",
      entrance: "Kirish",
      apartment: "Kvartira",
      yourOrder: "Sizning buyurtmangiz",
      products: "Buyurtmalar",
      delivery: "Yetgazib berish",
      payment: "To'lash uchun",
      method: "To'lov turi",
      card: "Bank kartasi",
      cash: "Naqt pul",
      promocode: "Promokodingiz bormi?",
      numberOfRecipient: "Qabul giluvchining raqami",
      endButton: "Buyurtani tugatish",
    },
    ordered: {
      firstMessage: "Sizning buyurtmangiz raqami №",
      secondMessage: "siz bilan menejerlarimiz bog'lanishadi.",
    },
  },
  ru: {
    footer: {
      saved: "Избранное",
      backed: "Корзина",
      contacts: "Контакты",
      service: "Условия сервиса",
    },
    service: {
      title: "Условия сервиса",
      text: "Задача организации, в особенности же курс на социально-ориентированный национальный проект требует от нас системного анализа модели развития! Таким образом, постоянное информационно-техническое обеспечение нашей деятельности требует от нас анализа системы масштабного изменения ряда параметров! С другой стороны социально-экономическое развитие напрямую зависит от всесторонне сбалансированных нововведений?",
    },
    contacts: {
      title: "Наш офис",
    },
    saved: {
      title: "Избранное",
    },
    emptybacked: {
      title: "Корзина пуста",
      text: "Но это никогда не поздно исправить :)",
      button: "В каталог товаров",
    },
    product: {
      characteristicsTitle: "Описание и характеристики",
      buttonBuy: "Купить!",
      addToBacked: "Добавить в корзину",
    },
    cart: {
      title: "Корзина",
      delivery: "Доставка",
      noDelivery: "Без доставки",
      byCourier: "Доставка курьером",
      total: "Итого",
      button: "Перейти к оформлению",
    },
    ordering: {
      title: "Оформление заказа",
      addressTitle: "Доставка курьером",
      address: "Адрес доставки",
      city: "Город",
      street: "Улица / Район",
      house: "Дом",
      entrance: "Подъезд",
      apartment: "Квартира",
      yourOrder: "Ваш заказ",
      products: "Товары",
      delivery: "Доставка",
      payment: "К оплате",
      method: "Способ оплаты",
      card: "Банковская карта",
      cash: "Наличные",
      promocode: "Есть промокод?",
      numberOfRecipient: "Номер получателя",
      endButton: "Закончить оформление",
    },
    ordered: {
      firstMessage: "Номер вашего заказа №",
      secondMessage: "с Вами свяжется наш менеджер.",
    },
  },
  en: {
    footer: {
      saved: "Favorites",
      backed: "Backed",
      contacts: "Contacts",
      service: "Service requivements",
    },
    service: {
      title: "Service requivements",
      text: "The task of the organization, especially the course towards a socially oriented national project, requires us to systematically analyze the development model! Thus, continuous information technology support of our activities requires us to analyze the system of large-scale change of a number of parameters! On the other hand, is economic and social development directly dependent on well-balanced innovation?",
    },
    contacts: {
      title: "Our office",
    },
    saved: {
      title: "Favorites",
    },
    emptybacked: {
      title: "Backed is empty",
      text: "But it's never late to fix it :)",
      button: "To product catalog",
    },
    product: {
      characteristicsTitle: "Description and characteristics",
      buttonBuy: "Buy!",
      addToBacked: "Add to backed",
    },
    cart: {
      title: "Cart",
      delivery: "Delivery",
      noDelivery: "Without delivery",
      byCourier: "Delivery by courier",
      total: "Total",
      button: "Proceed to checkout",
    },
    ordering: {
      title: "Ordering",
      addressTitle: "Delivery by courier",
      address: "Address of delivery",
      city: "City",
      street: "Street / District",
      house: "House",
      entrance: "Entrance",
      apartment: "Apartment",
      yourOrder: "Your order",
      products: "Products",
      delivery: "Delivery",
      payment: "For payment",
      method: "Payment method",
      card: "Credid card",
      cash: "Cash",
      promocode: "Got a promocade?",
      numberOfRecipient: "Number of recipients",
      endButton: "End the ordering",
    },
    ordered: {
      firstMessage: "Your order number is №",
      secondMessage: "our manager will contact you.",
    },
  },
};

export default languages;
